# -*- coding: utf-8 -*-
"""Copia de PREDICCION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXqbWXt2UhDF6iKEZ_8no6GRUaFNMEim

#### Install yfinance

aqui empieza el otro modelo



import yfinance as yf
import pandas as pd
#from fbprophet import Prophet

import matplotlib.pyplot as plt

def prediccionLinial():
    # berkshire hathaway inc. (b stock)
    brk = yf.Ticker('AMZN')
    hist = brk.history(start="2015-01-01", end="2022-04-30", auto_adjust=True)
    hist2 = brk.history(period='max', auto_adjust=True)



    df = pd.DataFrame()

    df['ds'] = hist.index
    df['y'] = hist['Close'].values

    ##Dataframe de prediccion

    df2 = pd.DataFrame()

    df2['ds'] = hist2.index
    df2['y'] = hist2['Close'].values



    m = Prophet(daily_seasonality=False)

    m.fit(df)

    future = m.make_future_dataframe(500, freq='D')

    forecast = m.predict(future)


    df2.ds= pd.to_datetime(df2.ds)
    ff=forecast[forecast.ds>'2022-01-02']
    ff2=ff[ff.ds<'2022-05-09']
    ff3=ff[['ds','yhat','yhat_lower','yhat_upper']]

    ff4=ff3[['ds','yhat']]
    #fechas similares a la grafica de regresion lineal de PREDICCION

    ff4= ff4[ff4['ds'] >='2022-05-15']
    ff4= ff4[ff4['ds'] <='2023-01-20']

    ff4["diferencia"]=ff4.yhat.diff()

    dfPRpos = ff4[ff4['diferencia'] >0 ]
    dfPRpos["diferencia"]=dfPRpos.yhat.diff()
    dfPRpos = dfPRpos[dfPRpos['diferencia'] >0 ]
    dfPRpos

    #suavizando con suavidad
    plt.figure(figsize=(15, 7.5))
    plt.plot(dfPRpos['ds'],dfPRpos['yhat'])

prediccionLinial()"""